import { env } from "cloudflare:workers";
import { currentMember } from "@/lib/access";
const statements=[
"CREATE TABLE IF NOT EXISTS improvements (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, category TEXT NOT NULL, owner TEXT NOT NULL, impact TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS runbooks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, product TEXT NOT NULL, environment TEXT NOT NULL, architecture TEXT NOT NULL, approval TEXT NOT NULL, owner TEXT NOT NULL, reviewed_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS skill_assessments (id INTEGER PRIMARY KEY AUTOINCREMENT, engineer TEXT NOT NULL, skill TEXT NOT NULL, rating TEXT NOT NULL, evidence TEXT NOT NULL, updated_at TEXT NOT NULL)"];
async function ready(){await env.DB.batch(statements.map(x=>env.DB.prepare(x)))}
export async function GET(request:Request){if(!await currentMember(request))return Response.json({error:"Access denied"},{status:403});await ready();const type=new URL(request.url).searchParams.get("type");const table=type==="improvements"?"improvements":type==="runbooks"?"runbooks":"skill_assessments";const {results}=await env.DB.prepare(`SELECT * FROM ${table} ORDER BY ${table==="skill_assessments"?"updated_at":"created_at"} DESC`).all();return Response.json({records:results})}
export async function POST(request:Request){if(!await currentMember(request))return Response.json({error:"Access denied"},{status:403});await ready();const {type,...body}=await request.json();const now=new Date().toISOString();if(type==="improvements"){await env.DB.prepare("INSERT INTO improvements (title,category,owner,impact,status,created_at) VALUES (?,?,?,?,?,?)").bind(body.title,body.category,body.owner,body.impact,"Proposed",now).run()}else if(type==="runbooks"){await env.DB.prepare("INSERT INTO runbooks (title,product,environment,architecture,approval,owner,reviewed_at) VALUES (?,?,?,?,?,?,?)").bind(body.title,body.product,body.environment,body.architecture,"Review needed",body.owner,now).run()}else{await env.DB.prepare("INSERT INTO skill_assessments (engineer,skill,rating,evidence,updated_at) VALUES (?,?,?,?,?)").bind(body.engineer,body.skill,body.rating,body.evidence,now).run()}return Response.json({ok:true},{status:201})}
