"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Engagement = { id:number; customer:string; title:string; products:string; environment:string; architecture:string; status:string; owner:string; updatedAt:string; progress?:string; nextStep?:string; risk?:string };
const statuses=["Not started","In progress","Awaiting customer","Blocked","Completed"];
const runbooks=[["Nexus Repository HA on AWS","Nexus Repository · AWS · HA","Approved"],["TLS and reverse-proxy validation","All products · On-premises · Networking","Approved"],["Lifecycle onboarding readiness","Lifecycle · Kubernetes · Installation","Approved"],["Repository Firewall rollout","Repository Firewall · On-premises · Configuration","Review needed"]];
const nav=["My work","Team pulse","Insights","Runbook library","Improvements","Growth"];
function Badge({status}:{status:string}){return <span className={`status ${status.toLowerCase().replaceAll(" ","-").replaceAll("/","")}`}>{status}</span>}

export default function Home(){
 const [section,setSection]=useState("Team pulse"),[filter,setFilter]=useState("All"),[records,setRecords]=useState<Engagement[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[update,setUpdate]=useState<Engagement|null>(null),[newEngagement,setNewEngagement]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);const r=await fetch("/api/engagements");const j=await r.json();setRecords(j.engagements??[]);setLoading(false)};useEffect(()=>{load()},[]);
 const shown=useMemo(()=>records.filter(r=>(filter==="All"||r.status===filter)&&`${r.customer} ${r.title} ${r.products} ${r.environment}`.toLowerCase().includes(query.toLowerCase())),[records,filter,query]);
 const counts=(status:string)=>records.filter(x=>x.status===status).length;
 async function submitUpdate(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!update)return;const f=new FormData(event.currentTarget);const r=await fetch("/api/updates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({engagementId:update.id,status:f.get("status"),progress:f.get("progress"),nextStep:f.get("nextStep"),risk:f.get("risk"),submittedBy:"Pilot engineer"})});if(r.ok){setUpdate(null);setMessage("Weekly update submitted. Your team pulse is current.");load()}}
 async function createEngagement(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const r=await fetch("/api/engagements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});if(r.ok){setNewEngagement(false);setMessage("Engagement created and ready for its first weekly update.");load()}}
 return <main className="app"><aside><div className="brand"><b>D</b><span>Delivery<br/><strong>Pulse</strong></span></div><p className="label">SOLUTION DELIVERY ENGINEERING</p><nav>{nav.map(x=><button className={x===section?"active":""} onClick={()=>setSection(x)} key={x}>{x}</button>)}</nav><div className="user"><i>KV</i><span><strong>Kshitij Vatsa</strong><small>Manager · SDE</small></span></div></aside><section className="body"><header><div><p className="label">PILOT WORKSPACE</p><h1>{section==="Team pulse"?"Your team, clearly in motion.":section}</h1></div><div><button className="secondary" onClick={()=>setNewEngagement(true)}>+ Engagement</button><button className="primary" onClick={()=>setUpdate(records[0]??null)}>+ Weekly update</button></div></header>{message&&<div className="notice">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 {section==="Team pulse"&&<><section className="signal"><div><p className="label">TEAM SIGNAL</p><h2>{counts("Blocked")?"Delivery is steady. One blocker needs intervention.":"Delivery is moving without active blockers."}</h2><p>{records.length} engagements are tracked in the pilot. Weekly updates become the shared operating record.</p></div><div className="signalStats"><span><b>{records.filter(x=>x.status!=="Completed").length}</b>active items</span><span><b>{counts("Blocked")}</b>blockers</span><span><b>{records.filter(x=>x.progress).length}</b>weekly updates</span></div></section><div className="metrics"><Card n={counts("In progress")} t="In progress" foot="Active delivery"/><Card n={counts("Awaiting customer")} t="Awaiting customer" foot="Follow-up due"/><Card n={counts("Blocked")} t="Blocked" foot="Needs attention" red/><Card n={counts("Completed")} t="Completed" foot="Delivery outcomes"/></div><section className="panel"><div className="heading"><div><h2>Engagement pulse</h2><p>Live state from submitted weekly updates</p></div><div className="filters">{["All",...statuses].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="table"><div className="tr th"><span>ENGAGEMENT</span><span>STATUS</span><span>THIS WEEK</span><span>NEXT STEP</span><span>UPDATED</span></div>{loading?<p>Loading engagements…</p>:shown.map(x=><div className="tr" key={x.id}><span><strong>{x.customer}</strong><small>{x.title} · {x.environment} · {x.architecture}</small></span><span><Badge status={x.status}/></span><span>{x.progress??"No weekly update yet"}<small className={x.risk&&x.risk!=="None"?"risk":""}>{x.risk??""}</small></span><span>{x.nextStep??"Add the first weekly update"}</span><span>{new Date(x.updatedAt).toLocaleDateString()}</span></div>)}</div></section><div className="two"><section className="panel"><p className="label">IMPROVEMENTS</p><h2>Make the next delivery easier.</h2><p>Capture documentation, process, automation, and knowledge contributions independently from customer work.</p><button className="secondary" onClick={()=>setSection("Improvements")}>Open improvements</button></section><section className="panel"><p className="label">TEAM DEVELOPMENT</p><h2>Architecture readiness</h2><p>Track separate capability evidence for HA, resiliency/DR, capacity sizing, cloud-native patterns, and distribution.</p><button className="secondary" onClick={()=>setSection("Growth")}>Open growth plan</button></section></div></>}
 {section==="My work"&&<Empty title="Keep the week current without daily reporting pressure." text="Open any engagement, add an optional note during the week, and submit one clear weekly update." action="Create weekly update" click={()=>setUpdate(records[0]??null)}/>} {section==="Improvements"&&<Empty title="Improvements that make the next delivery easier." text="This next build slice will store documentation, process, automation, and knowledge contributions with impact evidence." action="Coming next"/>}
 {section==="Insights"&&<div className="two"><section className="panel insight"><p className="label">PILOT METRICS</p><h2>Current delivery outcomes</h2><b>{counts("Completed")} <small>completed engagements</small></b><div className="bars"><i/><i/><i/><i/><i/></div></section><section className="panel"><p className="label">RECURRING THEME</p><h2>Architecture readiness</h2><p>Once the pilot has four weeks of data, this view will surface repeated blockers, product coverage, and course recommendations.</p></section></div>}
 {section==="Runbook library"&&<section className="panel"><div className="heading"><div><p className="label">APPROVED KNOWLEDGE</p><h2>Runbook library</h2><p>Find customer-safe guidance by product, environment, and architecture.</p></div><input placeholder="Search runbooks" value={query} onChange={e=>setQuery(e.target.value)}/></div>{runbooks.filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase())).map(r=><div className="runbook" key={r[0]}><span><em className={r[2]==="Approved"?"approved":"review"}>{r[2]}</em><h3>{r[0]}</h3><small>{r[1]}</small></span><small>Curated pilot content</small></div>)}</section>}
 {section==="Growth"&&<section className="panel"><div className="heading"><div><p className="label">SKILL COVERAGE</p><h2>Growth plan</h2><p>Separate product and architecture ratings, grounded in delivery evidence.</p></div></div>{[["Nexus Repository","Independent","2 active engagements"],["High availability","Working","Development action needed"],["Cloud-native architecture","Independent","AWS reference design applied"],["Resiliency & disaster recovery","Learning","Recommended: guided design review"],["Customer screen-share guidance","Advanced","4 approved command guides"]].map(r=><div className="skill" key={r[0]}><strong>{r[0]}</strong><em className={r[1].toLowerCase()}>{r[1]}</em><small>{r[2]}</small></div>)}</section>}
 </section>{update&&<UpdateModal record={update} close={()=>setUpdate(null)} submit={submitUpdate}/>} {newEngagement&&<EngagementModal close={()=>setNewEngagement(false)} submit={createEngagement}/>}</main>}
function Card({n,t,foot,red}:{n:number;t:string;foot:string;red?:boolean}){return <article><p>{t}</p><b>{n}</b><small className={red?"red":"green"}>{foot}</small></article>};function Empty({title,text,action,click}:{title:string;text:string;action:string;click?:()=>void}){return <section className="panel empty"><p className="label">PERSONAL WORKSPACE</p><h2>{title}</h2><p>{text}</p><button className="primary" onClick={click}>{action}</button></section>}
function UpdateModal({record,close,submit}:{record:Engagement;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="overlay"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="label">WEEKLY UPDATE · {record.customer.toUpperCase()}</p><h2>What materially changed this week?</h2><label>Progress<textarea name="progress" defaultValue={record.progress??""} required/></label><label>Current state<select name="status" defaultValue={record.status}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Next step and owner<textarea name="nextStep" defaultValue={record.nextStep??""} required/></label><label>Risk / blocker<textarea name="risk" defaultValue={record.risk??"None"} required/></label><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Submit weekly update</button></footer></form></div>}
function EngagementModal({close,submit}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="overlay"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="label">NEW ENGAGEMENT</p><h2>Add an engagement</h2><label>Customer<input name="customer" required/></label><label>Work title<input name="title" placeholder="e.g. Nexus Repository HA deployment" required/></label><label>Product(s)<input name="products" placeholder="Nexus Repository, IQ Server…" required/></label><label>Environment<select name="environment"><option>AWS</option><option>Azure</option><option>GCP</option><option>On-premises</option><option>Kubernetes</option><option>OpenShift</option></select></label><label>Architecture<select name="architecture"><option>Single node</option><option>HA</option><option>Resiliency / DR</option><option>Scalability / distribution</option><option>Migration / upgrade</option></select></label><label>Owner<input name="owner" placeholder="Engineer name" required/></label><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Create engagement</button></footer></form></div>}
