"use client";
import { useState } from "react";
type Status = "In progress" | "Awaiting customer" | "Blocked" | "Completed";
const work = [
  ["Apex Financial","Nexus Repository HA deployment","AWS · HA","In progress","Cluster prerequisites validated; database design review complete.","Confirm load balancer configuration — Customer","TLS certificate chain pending","Today"],
  ["Northstar Health","Lifecycle onboarding","Kubernetes","Awaiting customer","Application inventory and policy objectives shared.","Provide SSO metadata — Customer","None","Today"],
  ["Orbit Commerce","Repository Firewall rollout","On-premises","Blocked","Network connectivity test did not complete.","Resolve outbound proxy rule — Customer IT","Outbound access blocked since Aug 25","Yesterday"],
  ["Luma Energy","Nexus upgrade planning","Azure · Migration","Completed","Upgrade plan, validation checklist, and rollback path approved.","Schedule implementation window — Manager","None","Aug 25"],
] as const;
const runbooks = [["Nexus Repository HA on AWS","Nexus Repository · AWS · HA","Approved"],["TLS and reverse-proxy validation","All products · On-premises · Networking","Approved"],["Lifecycle onboarding readiness","Lifecycle · Kubernetes · Installation","Approved"],["Repository Firewall rollout","Repository Firewall · On-premises · Configuration","Review needed"]];
const nav = ["My work","Team pulse","Insights","Runbook library","Improvements","Growth"];
function Badge({status}:{status:string}) { return <span className={`status ${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span>; }
export default function Home(){
 const [section,setSection]=useState("Team pulse"),[filter,setFilter]=useState("All"),[modal,setModal]=useState(false),[submitted,setSubmitted]=useState(false),[query,setQuery]=useState("");
 const active=work.filter(x=>(filter==="All"||x[3]===filter)&&x.join(" ").toLowerCase().includes(query.toLowerCase()));
 return <main className="app"><aside><div className="brand"><b>D</b><span>Delivery<br/><strong>Pulse</strong></span></div><p className="label">SOLUTION DELIVERY ENGINEERING</p><nav>{nav.map(x=><button className={x===section?"active":""} onClick={()=>setSection(x)} key={x}>{x}</button>)}</nav><div className="user"><i>KV</i><span><strong>Kshitij Vatsa</strong><small>Manager · SDE</small></span></div></aside><section className="body"><header><div><p className="label">WEEK OF AUGUST 24–28</p><h1>{section==="Team pulse"?"Your team, clearly in motion.":section}</h1></div><div><button className="secondary">Export weekly brief</button><button className="primary" onClick={()=>{setSubmitted(false);setModal(true)}}>+ Weekly update</button></div></header>
 {section==="Team pulse"&&<><section className="signal"><div><p className="label">TEAM SIGNAL</p><h2>Delivery is steady. One blocker needs intervention.</h2><p>3 engineers are active across 4 customer engagements. Two customer-facing next steps are due this week.</p></div><div className="signalStats"><span><b>4</b>active items</span><span><b>1</b>blocker</span><span><b>92%</b>weekly updates</span></div></section><div className="metrics"><Card n="1" t="In progress" foot="On track"/><Card n="1" t="Awaiting customer" foot="Follow-up due"/><Card n="1" t="Blocked" foot="Needs attention" red/><Card n="1" t="Completed this week" foot="+1 from last week"/></div><section className="panel"><div className="heading"><div><h2>Engagement pulse</h2><p>Current state from this week’s updates</p></div><div className="filters">{["All","In progress","Awaiting customer","Blocked","Completed"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="table"><div className="tr th"><span>ENGAGEMENT</span><span>STATUS</span><span>THIS WEEK</span><span>NEXT STEP</span><span>UPDATED</span></div>{active.map(x=><div className="tr" key={x[0]}><span><strong>{x[0]}</strong><small>{x[1]} · {x[2]}</small></span><span><Badge status={x[3]}/></span><span>{x[4]}<small className={x[6]==="None"?"":"risk"}>{x[6]==="None"?"No risk recorded":`Risk: ${x[6]}`}</small></span><span>{x[5]}</span><span>{x[7]}</span></div>)}</div></section><div className="two"><section className="panel"><div className="heading"><div><h2>Bright spots</h2><p>Evidence worth recognizing</p></div><button className="text">View all</button></div><p className="feed"><i>PS</i><span><strong>Priya</strong> completed the Luma Energy upgrade plan with validated rollback guidance.<small>Documentation contribution · Nexus Repository</small></span></p><p className="feed"><i>DK</i><span><strong>Daniel</strong> created a reusable Lifecycle onboarding checklist.<small>Improvement · Available for review</small></span></p></section><section className="panel"><div className="heading"><div><h2>Needs attention</h2><p>Intervene before these age</p></div></div><p className="attention"><b>1</b><span><strong>Orbit Commerce network access</strong><small>Blocked 2 days · Owner: Customer IT</small></span><button className="secondary">Escalate</button></p><p className="attention"><b>2</b><span><strong>Northstar SSO metadata</strong><small>Awaiting customer · Follow up tomorrow</small></span><button className="secondary">Nudge</button></p></section></div></>}
 {section==="My work"&&<Empty title="Keep the week current without daily reporting pressure." text="Record an optional daily note, then submit one clear weekly update for each active engagement." action="Create weekly update" click={()=>setModal(true)}/>} {section==="Improvements"&&<Empty title="Improvements that make the next delivery easier." text="Track documentation, process, automation, and knowledge contributions separately from customer work." action="+ Log improvement"/>}
 {section==="Insights"&&<div className="two"><section className="panel insight"><p className="label">LAST 90 DAYS</p><h2>Delivery outcomes</h2><b>18 <small>completed work items</small></b><div className="bars"><i/><i/><i/><i/><i/></div></section><section className="panel"><p className="label">RECURRING THEME</p><h2>Architecture readiness</h2><p>Networking/TLS and HA design show up most often in risks and documentation gaps.</p><button className="secondary">Open improvement plan</button></section></div>}
 {section==="Runbook library"&&<section className="panel"><div className="heading"><div><p className="label">APPROVED KNOWLEDGE</p><h2>Runbook library</h2><p>Find customer-safe guidance by product, environment, and architecture.</p></div><input placeholder="Search runbooks" value={query} onChange={e=>setQuery(e.target.value)}/></div>{runbooks.filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase())).map(r=><div className="runbook" key={r[0]}><span><em className={r[2]==="Approved"?"approved":"review"}>{r[2]}</em><h3>{r[0]}</h3><small>{r[1]}</small></span><small>Reviewed Aug 22</small></div>)}</section>}
 {section==="Growth"&&<section className="panel"><div className="heading"><div><p className="label">SKILL COVERAGE</p><h2>Growth plan</h2><p>Separate product and architecture ratings, grounded in delivery evidence.</p></div><button className="secondary">Start assessment</button></div>{[["Nexus Repository","Independent","2 active engagements"],["High availability","Working","Development action needed"],["Cloud-native architecture","Independent","AWS reference design applied"],["Resiliency & disaster recovery","Learning","Recommended: guided design review"],["Customer screen-share guidance","Advanced","4 approved command guides"]].map(r=><div className="skill" key={r[0]}><strong>{r[0]}</strong><em className={r[1].toLowerCase()}>{r[1]}</em><small>{r[2]}</small></div>)}</section>}
 </section>{modal&&<div className="overlay"><section className="modal"><button className="close" onClick={()=>setModal(false)}>×</button>{submitted?<div className="success"><b>✓</b><h2>Weekly update submitted</h2><p>Your team pulse and reporting views are now current.</p><button className="primary" onClick={()=>setModal(false)}>Done</button></div>:<><p className="label">WEEKLY UPDATE · APEX FINANCIAL</p><h2>What materially changed this week?</h2><label>Progress<textarea defaultValue="Cluster prerequisites validated; database design review complete."/></label><label>Current state<select><option>In progress</option><option>Awaiting customer</option><option>Blocked</option><option>Completed</option></select></label><label>Next step and owner<textarea defaultValue="Confirm load balancer configuration — Customer"/></label><label>Risk / blocker<textarea defaultValue="TLS certificate chain pending"/></label><footer><button className="secondary" onClick={()=>setModal(false)}>Save draft</button><button className="primary" onClick={()=>setSubmitted(true)}>Submit weekly update</button></footer></>}</section></div>}</main> }
function Card({n,t,foot,red}:{n:string;t:string;foot:string;red?:boolean}){return <article><p>{t}</p><b>{n}</b><small className={red?"red":"green"}>{foot}</small></article>};function Empty({title,text,action,click}:{title:string;text:string;action:string;click?:()=>void}){return <section className="panel empty"><p className="label">PERSONAL WORKSPACE</p><h2>{title}</h2><p>{text}</p><button className="primary" onClick={click}>{action}</button></section>}
